// import { useState } from "react"
// import dynamic from "next/dynamic"
// const Spline = dynamic(() => import("@splinetool/react-spline"), {
//   ssr: false,
// })

// export default function GoldMaskLogo() {
//   const [spline, setSpline] = useState<any>()

//   function onLoad() {
//     setSpline(spline)
//     console.log("inside onLoad")
//     spline?.emitEvent("mouseHover", "d8bfa08b-1e2c-4511-8f4c-f75e709396c1")
//     window.dispatchEvent(new Event("resize"))
//   }

//   return (
//     <Spline
//       scene="https://prod.spline.design/QZQ39MAcUPi3F1Dl/scene.splinecode"
//       onLoad={onLoad}
//       className="absolute inset-0"
//     />
//   )
// }

/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline"
import { OrthographicCamera } from "@react-three/drei"

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline("https://prod.spline.design/vTxs1ecD-HPjDCO7/scene.splinecode")
  return (
    <>
      {/* <color attach="background" args={["#4b4d52"]} /> */}
      <group {...props} dispose={null}>
        <OrthographicCamera
          name="Camera"
          makeDefault={true}
          far={100000}
          near={-100000}
          position={[-2000, 2000, 8000]}
          zoom={0.2}
        />
        <group
          name="lights"
          // position={[-488.7, 19.57, 7369.65]}
          position={[1000, 2500, 9000]}
        >
          <spotLight
            name="Spot Light 8"
            intensity={0.14}
            angle={0.07}
            penumbra={1}
            decay={0}
            distance={2290}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-fov={119.99999999999999}
            shadow-camera-near={100}
            shadow-camera-far={100000}
            color="#b08a00"
            position={[518.73, -260.4, -6700.51]}
            rotation={[1.64, -0.04, 0]}
          />
          <spotLight
            name="Spot Light 6"
            intensity={1.8}
            angle={0.66}
            penumbra={0.4}
            decay={0}
            distance={2332}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-fov={119.99999999999999}
            shadow-camera-near={100}
            shadow-camera-far={100000}
            color="#a58315"
            position={[1461.66, -488.81, -5975.36]}
            rotation={[1.52, -0.36, -0.9]}
          />
          <spotLight
            name="Spot Light 5"
            intensity={0.6}
            angle={Math.PI / 5}
            penumbra={0.6}
            decay={0}
            distance={2491}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-fov={119.99999999999999}
            shadow-camera-near={100}
            shadow-camera-far={100000}
            color="#a38812"
            position={[-1041.93, -1356.32, -6061.67]}
            rotation={[1.66, 0.13, 0.98]}
          />
        </group>
        <directionalLight
          name="Directional Light"
          intensity={0.2}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-500}
          shadow-camera-right={500}
          shadow-camera-top={500}
          shadow-camera-bottom={-500}
          color="#a0e985"
          // position={[-165.16, -63.44, 142.34]}
          position={[2000, 2000, 100]}
        />
        <mesh
          name="Rectangle"
          geometry={nodes.Rectangle.geometry}
          material={materials["Rectangle Material"]}
          position={[-1366.07, 1494.17, -8615.06]}
          scale={[3.43, 2.31, 1.97]}
        />
        <group name="Mask" scale={30} position={[800, 1000, 1000]}>
          <mesh
            name="Extract5"
            geometry={nodes.Extract5.geometry}
            material={nodes.Extract5.material}
            castShadow
            receiveShadow
            position={[-13.7, -853.36, 33.23]}
            rotation={[-0.09, 0.02, 0]}
          />
        </group>
        <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#e4be00" position={[0, 1, 0]} />
      </group>
    </>
  )
}

/*
  Auto-generated by Spline
*/

// import useSpline from "@splinetool/r3f-spline"
// import { PerspectiveCamera } from "@react-three/drei"

// export default function Scene({ ...props }) {
//   const { nodes, materials } = useSpline("https://prod.spline.design/ZFJJq5coQUEdE-vQ/scene.splinecode")
//   return (
//     <>
//       <color attach="background" args={["#beb8b8"]} />
//       <group {...props} dispose={null}>
//         <PerspectiveCamera
//           name="Camera"
//           makeDefault={true}
//           far={100000}
//           near={5}
//           fov={45}
//           position={[-295.28, 2366.9, 4578.15]}
//         />
//         <group name="Group 2" position={[-229.18, 3048.95, 3741.66]}>
//           <spotLight
//             name="Spot Light 4"
//             castShadow
//             intensity={2}
//             angle={Math.PI / 2}
//             distance={8343}
//             shadow-mapSize-width={1024}
//             shadow-mapSize-height={1024}
//             shadow-camera-fov={119.99999999999999}
//             shadow-camera-near={100}
//             shadow-camera-far={100000}
//             color="#e7c300"
//             position={[229.18, -903.92, -4757.93]}
//             rotation={[1.58, 0, 0]}
//           />
//           <spotLight
//             name="Spot Light 3"
//             castShadow
//             intensity={6.3}
//             angle={0.33}
//             distance={10000}
//             shadow-mapSize-width={1024}
//             shadow-mapSize-height={1024}
//             shadow-camera-fov={119.99999999999999}
//             shadow-camera-near={100}
//             shadow-camera-far={100000}
//             color="#e7c300"
//             position={[293.03, 247.25, 4756.28]}
//             rotation={[1.48, 0, -0.04]}
//           />
//           <spotLight
//             name="Spot Light 2"
//             castShadow
//             intensity={4.7}
//             angle={0.72}
//             penumbra={0.4}
//             decay={1.6}
//             distance={10000}
//             shadow-mapSize-width={1024}
//             shadow-mapSize-height={1024}
//             shadow-camera-fov={119.99999999999999}
//             shadow-camera-near={100}
//             shadow-camera-far={100000}
//             color="#e3ca00"
//             position={[-4541.85, 381.67, -1944.74]}
//             rotation={[1.37, 0.08, 1.17]}
//           />
//           <spotLight
//             name="Spot Light"
//             castShadow
//             intensity={2.8}
//             angle={0.75}
//             penumbra={0.4}
//             decay={1.4}
//             distance={10000}
//             shadow-mapSize-width={1024}
//             shadow-mapSize-height={1024}
//             shadow-camera-fov={119.99999999999999}
//             shadow-camera-near={100}
//             shadow-camera-far={100000}
//             color="#e3ca00"
//             position={[4541.13, 898.82, -2650.62]}
//             rotation={[1.74, 0.23, -1.3]}
//           />
//         </group>
//         <group name="Group 3" position={[500, 211.06, -370.64]} rotation={[-0.01, 0, -0.01]}>
//           <group name="Group" rotation={[0.3, -0.31, 0.01]} scale={25.34}>
//             <mesh
//               name="meshes[0]"
//               geometry={nodes["meshes[0]"].geometry}
//               material={nodes["meshes[0]"].material}
//               castShadow
//               receiveShadow
//               position={[161.58, -736.33, 326.95]}
//               rotation={[-0.49, 0.23, 0.12]}
//             />
//             <mesh
//               name="meshes[1]"
//               geometry={nodes["meshes[1]"].geometry}
//               material={nodes["meshes[1]"].material}
//               castShadow
//               receiveShadow
//               position={[161.58, -736.33, 326.95]}
//               rotation={[-0.49, 0.23, 0.12]}
//             />
//           </group>
//         </group>
//         <mesh
//           name="Cube"
//           geometry={nodes.Cube.geometry}
//           material={materials["Cube Material"]}
//           castShadow
//           receiveShadow
//           position={[-493.98, 2413.44, -7040.86]}
//           rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
//           scale={[16.33, 14.82, 14.82]}
//         />
//         <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" position={[0, 1, 0]} />
//       </group>
//     </>
//   )
// }
